### ISSUE TITLE
Provide examples in project

### ISSUE THREAD

**Issue by demipixel** [motion-canvas/examples#1]
**Description**
While I understand aarthificial said they plan to make their video code open source, it could still be beneficial to have some smaller examples (beyond what's in the README) that are easier to digest to help people get started.

**What should example include?**

My proposal would be to have two examples:
1. An minimal, 1-2 file example including a single scene that performs some basic actions (creating basic shapes like Rect and Circle, usage of `yield` and `yield*` with position/rotation/scale, etc).
2. A more complex example with multiple scenes, including more advanced topics such as a custom `Shape`, transitions, flows (`all`, `sequence`, `delay`, etc), and whatever else.

**Setup**

Most projects typically have an `examples/` folder at the top level, which I think would be easiest for people to see and explore. Ideally, each example should be their own folder (with a `package.json` and such) so that they're immediately runnable. If that's the case, though, some steps might need to be taken to make them behave differently from a regular project (would need to include @motion-canvas/core locally rather than external from npm).

**Comment by aarthificial** [comment]
https://github.com/motion-canvas/motion-canvas/tree/main/packages/examples
