### ISSUE TITLE
Error with Audio when running deferred-lighting

### ISSUE THREAD

**Issue by NOT-HAL9000** [motion-canvas/examples#2]
Followed the instructions.

```npm install``` followed by ```npm run deferred-lighting```

Received the following error:

> Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data
> The problem occurred here:

![Screen Shot 2023-02-05 at 9 29 29 am](https://user-images.githubusercontent.com/70297791/216792352-b4dab03e-61be-4a23-92cf-592c956dd424.png)

Possibly related to chrome no-user-gesture-required policy.

**Comment by Mitra98t** [comment]
I have the same issue, on safari on mac os and chrome on windows

**Comment by Mitra98t** [comment]
Turns out reading more closely solved the issue for me: 
"Make sure that you have [Git LFS](https://git-lfs.github.com/) installed and that you cloned the project using git." 

if you go and install git LFS and then clone the repo the problem is solved @NOT-HAL9000

**Comment by m-roberts** [comment]
#3 is currently preventing this

**Comment by aarthificial** [comment]
LFS has been removed in #9
