### ISSUE TITLE
Not able to play deffered lighting examples . was able to play all other example 

### ISSUE THREAD

**Issue by fuhadabdulla** [motion-canvas/examples#5]
I am not able view the deffered lighting animation in the browser . code run successfully but i am not able play it . is it because my pc is not powerful . i was able to play other examples.

![image](https://user-images.githubusercontent.com/68536959/219842695-0015daf9-d33e-4ff2-9c8c-1c5ade17b7de.png)

**Comment by matdexir** [comment]
Same for me. I get two errors one is empty the other is about audio data.
![2023-02-27_18-05](https://user-images.githubusercontent.com/58453130/221534312-573b8ab9-1b23-4428-9eb9-46b655341a86.png)

**Comment by zd4y** [comment]
You have to [install git-lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage) and then run `git lfs pull`

**Comment by aarthificial** [comment]
LFS has been removed in #9
